-- INSERT assets from carteira-patrimonio-export-klb.xlsx
-- Target: strategy.tb_asset
--
-- Category / country IDs (from current DB):
--   category: 1 AÇÕES (BR), 2 FII (BR), 3 REIT (US), 4 STOCK (US), 5 ETF (US), 6 Tesouro SELIC (BR), 8 FIAGRO (BR)
--   country:  1 Brasil, 2 United State
--
-- sector_id / segment_id: best-effort from existing lookups; NULL when unknown — adjust as needed
-- Tesouro tickets shortened to fit length limit (SELIC25..SELIC31); originals were tesouro-selic-YYYY
-- Existing IRDM11 in DB is kept; Excel has IRIM11 (separate ticker)

INSERT INTO strategy.tb_asset
  (name, ticket, description, country_id, category_id, sector_id, segment_id, income_type, created_at, updated_at)
VALUES
  ('Banco do Brasil', 'BBAS3', 'Ações', 1, 1, 3, 10, 'VARIABLE', NOW(), NOW()),
  ('Bradesco ON', 'BBDC3', 'Ações', 1, 1, 3, 10, 'VARIABLE', NOW(), NOW()),
  ('BB Seguridade', 'BBSE3', 'Ações', 1, 1, 3, 12, 'VARIABLE', NOW(), NOW()),
  ('Caixa Seguridade', 'CXSE3', 'Ações', 1, 1, 3, 12, 'VARIABLE', NOW(), NOW()),
  ('Engie Brasil', 'EGIE3', 'Ações', 1, 1, 5, 11, 'VARIABLE', NOW(), NOW()),
  ('Isa Energia PN', 'ISAE4', 'Ações', 1, 1, 5, 11, 'VARIABLE', NOW(), NOW()),
  ('Klabin PN', 'KLBN4', 'Ações', 1, 1, 4, 9, 'VARIABLE', NOW(), NOW()),
  ('Petrobras PN', 'PETR4', 'Ações', 1, 1, 4, NULL, 'VARIABLE', NOW(), NOW()),
  ('Porto Seguro', 'PSSA3', 'Ações', 1, 1, 3, 12, 'VARIABLE', NOW(), NOW()),
  ('Irani', 'RANI3', 'Ações', 1, 1, 4, 9, 'VARIABLE', NOW(), NOW()),
  ('Santander Brasil ON', 'SANB3', 'Ações', 1, 1, 3, 10, 'VARIABLE', NOW(), NOW()),
  ('Sanepar Unit', 'SAPR11', 'Ações', 1, 1, 5, 11, 'VARIABLE', NOW(), NOW()),
  ('Taesa Unit', 'TAEE11', 'Ações', 1, 1, 5, 11, 'VARIABLE', NOW(), NOW()),
  ('Vale', 'VALE3', 'Ações', 1, 1, 4, NULL, 'VARIABLE', NOW(), NOW()),
  ('BC FFII', 'BRCR11', 'FIIs', 1, 2, 6, 3, 'VARIABLE', NOW(), NOW()),
  ('BTG Pactual Hipotecario', 'BTHF11', 'FIIs', 1, 2, 7, 5, 'VARIABLE', NOW(), NOW()),
  ('Capitania Securities', 'CPTS11', 'FIIs', 1, 2, 7, 5, 'VARIABLE', NOW(), NOW()),
  ('Devant Recebiveis', 'DEVA11', 'FIIs', 1, 2, 7, 5, 'VARIABLE', NOW(), NOW()),
  ('GGR Copart', 'GGRC11', 'FIIs', 1, 2, 8, 6, 'VARIABLE', NOW(), NOW()),
  ('Hedge Top FOFII', 'HFOF11', 'FIIs', 1, 2, 6, 1, 'VARIABLE', NOW(), NOW()),
  ('HSI Malls', 'HSML11', 'FIIs', 1, 2, 8, 2, 'VARIABLE', NOW(), NOW()),
  ('IRIM11', 'IRIM11', 'FIIs', 1, 2, 6, 1, 'VARIABLE', NOW(), NOW()),
  ('JS Real Estate', 'JSRE11', 'FIIs', 1, 2, 8, 4, 'VARIABLE', NOW(), NOW()),
  ('Kinea Renda Imobiliaria', 'KNRI11', 'FIIs', 1, 2, 6, 3, 'VARIABLE', NOW(), NOW()),
  ('VBI Logistico', 'LVBI11', 'FIIs', 1, 2, 8, 6, 'VARIABLE', NOW(), NOW()),
  ('VBI Prime Properties', 'PVBI11', 'FIIs', 1, 2, 8, 4, 'VARIABLE', NOW(), NOW()),
  ('Rio Bravo Renda Varejo', 'RBVA11', 'FIIs', 1, 2, 8, 8, 'VARIABLE', NOW(), NOW()),
  ('Sunelo FII', 'SNEL11', 'FIIs', 1, 2, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('TG Ativo Real', 'TGAR11', 'FIIs', 1, 2, 8, 7, 'VARIABLE', NOW(), NOW()),
  ('TRX Real Estate', 'TRXF11', 'FIIs', 1, 2, 8, 8, 'VARIABLE', NOW(), NOW()),
  ('Vinci Logistica', 'VILG11', 'FIIs', 1, 2, 8, 6, 'VARIABLE', NOW(), NOW()),
  ('Vinci Offices', 'VINO11', 'FIIs', 1, 2, 8, 4, 'VARIABLE', NOW(), NOW()),
  ('Vinci Shopping Centers', 'VISC11', 'FIIs', 1, 2, 8, 2, 'VARIABLE', NOW(), NOW()),
  ('XP Log', 'XPLG11', 'FIIs', 1, 2, 8, 6, 'VARIABLE', NOW(), NOW()),
  ('XP Malls', 'XPML11', 'FIIs', 1, 2, 8, 2, 'VARIABLE', NOW(), NOW()),
  ('Tesouro Selic 2025', 'SELIC25', 'Tesouro', 1, 6, NULL, NULL, 'FIXED', NOW(), NOW()),
  ('Tesouro Selic 2026', 'SELIC26', 'Tesouro', 1, 6, NULL, NULL, 'FIXED', NOW(), NOW()),
  ('Tesouro Selic 2027', 'SELIC27', 'Tesouro', 1, 6, NULL, NULL, 'FIXED', NOW(), NOW()),
  ('Tesouro Selic 2029', 'SELIC29', 'Tesouro', 1, 6, NULL, NULL, 'FIXED', NOW(), NOW()),
  ('Tesouro Selic 2031', 'SELIC31', 'Tesouro', 1, 6, NULL, NULL, 'FIXED', NOW(), NOW()),
  ('AbbVie', 'ABBV', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('AMD', 'AMD', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Amazon', 'AMZN', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Coinbase', 'COIN', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Enbridge', 'ENB', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Alphabet Class C', 'GOOG', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Main Street Capital', 'MAIN', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Meta Platforms', 'META', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Microsoft', 'MSFT', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Toronto-Dominion Bank', 'TD', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Verizon', 'VZ', 'Stocks', 2, 4, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Agree Realty', 'ADC', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('American Tower', 'AMT', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Alexandria Real Estate', 'ARE', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Broadstone Net Lease', 'BNL', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('BXP Inc', 'BXP', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Easterly Government Properties', 'DEA', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Digital Realty', 'DLR', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Getty Realty', 'GTY', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('LTC Properties', 'LTC', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Mid-America Apartment', 'MAA', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('NNN REIT', 'NNN', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('National Storage Affiliates', 'NSA', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Realty Income', 'O', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Public Storage', 'PSA', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Regency Centers', 'REG', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Simon Property Group', 'SPG', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('STAG Industrial', 'STAG', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Sun Communities', 'SUI', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('VICI Properties', 'VICI', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('W. P. Carey', 'WPC', 'REITS', 2, 3, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('XP Credito Agricola', 'XPCA11', 'FIAGRO', 1, 8, 6, 3, 'VARIABLE', NOW(), NOW()),
  ('WisdomTree US High Dividend', 'DHS', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('JPMorgan Equity Premium Income', 'JEPI', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('JPMorgan Nasdaq Equity Premium Income', 'JEPQ', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('iShares Preferred and Income Securities', 'PFF', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Invesco S&P 500 High Dividend Low Volatility', 'SPHD', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('iShares Treasury Floating Rate Bond', 'TFLO', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW()),
  ('Vanguard S&P 500 ETF', 'VOO', 'ETF Exterior', 2, 5, NULL, NULL, 'VARIABLE', NOW(), NOW());

-- Total: 79 assets